### ISSUE TITLE
Stop logo on boot

### ISSUE THREAD

**Issue by s-kk** [faithvoid/X1C1-Mojave#1]
Hello!
I really appreciate your effort on making hackintosh possible on such an old X1. I happen to have one and I had a try with your EFI.

But after I applied your efi, the stop logo appears every time I start hackintosh. And if I switch to my own efi, it's OK. 
I've done a bit research but nothing really helps.

Could you please dig a bit into this?
Thanks in advance!

**Comment by faithvoid** [comment]
hey there! is this pre or post installation?

i've heard from another user that the clover.plist file i uploaded for some reason doesn't allow installation, but works post-installation. if this is pre-installation, would you mind trying with a the barebones config.plist that comes with Clover to install, then replacing it with the config.plist from the GitHub post-install?

i'll have some more time to troubleshoot this over the weekend, but for now i'm replacing the config.plist file with the exact one i'm running on my system.

**Comment by faithvoid** [comment]
update: replaced the config.plist with the same one i'm running verbatim. let me know if this works for you or not! thanks for your bug report!

**Comment by s-kk** [comment]
Sorry for not replying. I’ve been busy for a while. 
The problem is resolved by replacing SMBIOS info. I’m guessing that the SMBIOS info in repo is not that consistent with the specs on X1C 1st gen. 

So, I’m closing this.
